name: Build

on:
  push:
    branches: master
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install node
      uses: actions/setup-node@v1
      with:
       node-version: '14.x'

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        architecture: 'x64'

    - name: Install dependencies
      run: python -m pip install jupyterlab --pre

    - name: Install the extension
      run: |
        python -m pip install -e .

    - name: Browser Check
      run: |
        python -m jupyterlab.browser_check
