name: Build

on:
  push:
    branches: master
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install node
      uses: actions/setup-node@v1
      with:
       node-version: '14.x'
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install jupyter_packaging
        python -m pip install --pre jupyterlab
    - name: Install the extension
      run: |
        python -m pip install .
        jupyter labextension develop . --overwrite
        jupyter labextension list 2>&1 | grep -ie "jupyterlab-python-file.*enabled.*ok" -
        python -m jupyterlab.browser_check
    - name: Lint
      run: |
        jlpm
        jlpm run eslint:check
        jlpm run prettier:check
